name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  ubuntu-nightly:
    runs-on: ubuntu-latest
    steps:     
      - name: install pkgs
        run: |
             sudo apt-get update && DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install vim python3 python3-pip python3-distutils python3-tk libpython3-dev libxmu-dev tk-dev tcl-dev cmake git g++ libglu1-mesa-dev libblas-dev liblapack-dev
             sudo apt-get install -y software-properties-common
             sudo add-apt-repository universe
             sudo add-apt-repository ppa:ngsolve/nightly -y
             sudo apt-get install ngsolve -y
      - name: set path
        run: |
             echo "PYTHONPATH=/usr/lib/python3/dist-packages/" >> $GITHUB_ENV
             echo "NETGENDIR=/usr/bin/" >> $GITHUB_ENV
      #- uses: actions/checkout@v2
      - name: get source
        run: git clone https://github.com/jayggg/ngstents ~/work/ngstents
      - name: cmake ngstents
        run: cmake -B~/work/ngstents/make -S~/work/ngstents/src/
      - name: compile ngstents
        run: |
             make -C~/work/ngstents/make
             sudo make -C/home/runner/work/ngstents/make install  
        
  macos-nightly:
    runs-on: macos-latest
    steps:     
      - name: install pkgs
        run: |
             brew install python
             wget https://www.asc.tuwien.ac.at/~mhochsteger/ngsolve/macos/NGSolve_nightly.dmg
             hdiutil attach NGSolve_nightly.dmg
             cp -R /Volumes/NGSolve/* /Applications
      - name: set path
        run: |
             echo "PYTHONPATH=$PYTHONPATH:/Applications/Netgen.app/Contents/Resources/lib/python3.8/site-packages:." >> $GITHUB_ENV
             echo "NETGENDIR=/Applications/Netgen.app/Contents/MacOS" >> $GITHUB_ENV
             echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$NETGENDIR" >> $GITHUB_ENV
             echo "DYLD_FRAMEWORK_PATH=$DYLD_FRAMEWORK_PATH:$NETGENDIR/../Frameworks" >> $GITHUB_ENV
             echo "$NETGENDIR" >> $GITHUB_PATH
      #- uses: actions/checkout@v2
      - name: get source
        run: git clone https://github.com/jayggg/ngstents ~/work/ngstents
      - name: cmake ngstents
        run: cmake -B~/work/ngstents/make -S~/work/ngstents/src/
      - name: compile ngstents
        run: |
             make -C~/work/ngstents/make
             sudo make -C~/work/ngstents/make install  

